const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const settingsSource = fs.readFileSync(path.resolve(__dirname, '..', 'shop_settings.html'), 'utf8');
const dialogHostSource = fs.readFileSync(path.resolve(__dirname, '..', '..', 'common', 'js', 'dialog_host.js'), 'utf8');

test('支付配置支持多服务商和买家端支付方式', () => {
  assert.match(settingsSource, /function paymentSettings\(\)/);
  assert.match(settingsSource, /Stripe/);
  assert.match(settingsSource, /空中云汇/);
  assert.match(settingsSource, /钱海/);
  assert.match(settingsSource, /PayPal/);
  assert.match(settingsSource, /Afterpay/);
  assert.match(settingsSource, /Visa、Mastercard/);
  assert.match(settingsSource, /function paymentMethodCatalog\(\)/);
  assert.match(settingsSource, /钱海支付/);
  assert.match(settingsSource, /空中云汇支付/);
  assert.match(settingsSource, /选择其他支付方式/);
  assert.match(settingsSource, /信用卡支付/);
  assert.match(settingsSource, /其他支付方式/);
  assert.match(settingsSource, /Stripe信用卡/);
  assert.match(settingsSource, /只能选择一家/);
  assert.match(settingsSource, /data-select-card-provider/);
  assert.match(settingsSource, /data-configure-card-provider/);
  assert.match(settingsSource, /data-configure-payment-provider/);
  assert.match(settingsSource, /data-save-payment-settings/);
  assert.match(settingsSource, /data-preview-payment-checkout/);
  assert.match(settingsSource, /查看买家端示例/);
  assert.match(settingsSource, /保存并生效/);
  assert.match(settingsSource, /data-payment-provider/);
  assert.match(settingsSource, /data-payment-method-summary/);
  assert.match(settingsSource, /draggable="true"/);
  assert.match(settingsSource, /已配置/);
  assert.match(settingsSource, /未配置/);
  assert.match(settingsSource, /rbk-payment-method-catalog-dialog/);
  assert.match(settingsSource, /rbk-payment-methods-saved/);
  assert.match(settingsSource, /selectedOtherMethods/);
  assert.match(settingsSource, /selectCardProviderButton/);
  assert.match(settingsSource, /rbk-payment-provider-dialog/);
  assert.match(settingsSource, /payment-method-manager/);
  assert.doesNotMatch(settingsSource, /data-payment-routing/);
  assert.doesNotMatch(settingsSource, /data-manage-other-providers/);
  assert.doesNotMatch(settingsSource, /Apple Pay/);
  assert.doesNotMatch(settingsSource, /Google Pay/);
  assert.doesNotMatch(settingsSource, /Klarna/);
  assert.doesNotMatch(settingsSource, /iDEAL/);
});

test('支付服务商配置由父级全屏对话框承载', () => {
  assert.match(dialogHostSource, /function openPaymentProviderDialog\(/);
  assert.match(dialogHostSource, /id = 'paymentProviderDialog'/);
  assert.match(dialogHostSource, /position:fixed;inset:0/);
  assert.match(dialogHostSource, /aria-modal="true"/);
  assert.match(dialogHostSource, /rbk-payment-provider-saved/);
  assert.match(dialogHostSource, /连接 Stripe/);
  assert.match(dialogHostSource, /连接 PayPal/);
  assert.match(dialogHostSource, /Unique client ID/);
  assert.match(dialogHostSource, /MerchantId/);
  assert.match(dialogHostSource, /终端号/);
  assert.match(dialogHostSource, /补充经营资料/);
  assert.match(dialogHostSource, /等待审核/);
  assert.doesNotMatch(dialogHostSource, /API 密钥/);
  assert.doesNotMatch(dialogHostSource, /Webhook 签名密钥/);
  assert.match(dialogHostSource, /function openPaymentRoutingDialog\(/);
  assert.match(dialogHostSource, /rbk-payment-routing-saved/);
  assert.match(dialogHostSource, /function openPaymentMethodCatalogDialog\(/);
  assert.match(dialogHostSource, /id = 'paymentMethodCatalogDialog'/);
  assert.match(dialogHostSource, /function openPaymentProviderCatalogDialog\(/);
  assert.match(dialogHostSource, /function openCreditCardProviderDialog\(/);
  assert.match(dialogHostSource, /function openPaymentActivationConfirmDialog\(/);
  assert.match(dialogHostSource, /确认保存并生效/);
  assert.match(dialogHostSource, /rbk-payment-activation-confirmed/);
  assert.match(dialogHostSource, /function openPaymentCheckoutPreviewDialog\(/);
  assert.match(dialogHostSource, /买家端支付方式示例/);
  assert.match(dialogHostSource, /配置收款服务商/);
  assert.doesNotMatch(dialogHostSource, /data-payment-method-move/);
  assert.match(dialogHostSource, /rbk-payment-methods-saved/);
});
